# NE HealthNet Backend Configuration
spring:
  application:
    name: ne-healthnet-backend
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:healthnetdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Kolkata
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 4000
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
jwt:
  secret: mySecretKeyForNEHealthNetApplication2024
  expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    com.healthnet: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# API Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

# Application Information
info:
  app:
    name: NE HealthNet Backend
    description: Northeast India Health Monitoring System - Java Backend
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17
